language: csharp
dist: bionic
mono: none
dotnet: 2.2
install:
- dotnet restore StepRedraw.UWP.sln
script:
- dotnet build -c Travis StepRedraw.UWP.sln
- dotnet test tests/StepRedraw.Math.Tests/StepRedraw.Math.Tests.csproj